document.getElementById("logo").addEventListener('click',abc)
//add classes
/*function abc(){
    document.getElementById("logo").classList.add("xxx");
}*/
// remove classes
/*function abc(){
    document.getElementById("logo").classList.remove("xxx");
}*/
//length of classes
/*function abc(){
    //document.getElementById("logo").classList.length;
    var a=document.getElementById("logo").classList.length;
    console.log(a);
}*/
// toggle classes
/*function abc(){
    document.getElementById("logo").classList.toggle("xxx");
}*/
// item class
/*function abc(){
   var a= document.getElementById("logo").classList.item(1);
   console.log(a);
}*/
// contain classea     check class exist or not
function abc(){
    var a=document.getElementById("logo").classList.contains("ddd");
    console.log(a);
}
