 // use parentelement 
 //return the parent if exist otherwise return null
/* var a =document.getElementById("inner").parentElement;
 console.log(a);*/
 /*ooter div parent in body
 var a =document.getElementById("outer").parentElement;
 console.log(a);*/ 
 // change in parent element through chid element
 /*document.getElementById("inner").parentElement.style.background="yellow";
 var a =document.getElementById("inner").parentElement;
 console.log(a);*/
 /*document.getElementById("n").parentElement.style.background="yellow";
 var a =document.getElementById("n").parentElement;
 console.log(a);*/
 //use parentnode
 //return text make it parent
 //document.getElementById("html").parentNode;
 var a =document.getElementById("m").parentNode;
 console.log(a);
